name: "clustalo_clustalo"
description: "Clustal Omega multiple sequence alignment program"
keywords:
  - multiple sequence alignment
  - msa
tools:
  - "clustalo":
      description: "Latest version of Clustal: a multiple sequence alignment program for DNA or proteins"
      homepage: "http://www.clustal.org/omega/"
      documentation: "http://www.clustal.org/omega/README"
      tool_dev_url: "None"
      doi: "10.1038/msb.2011.75"
      licence: "['GPL v2']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - fasta:
      type: file
      description: fasta file (can be compressed with gz)
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz,faa,faa.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - fasta:
      type: file
      description: Compressed multiple aligned fasta file
      pattern: "*.{mfa.gz}"

authors:
  - "@johannesnicolaus"
