name: "custom_separateorthologsr"
description: Separate orthologs to one fasta file per ortholog groups
keywords:
  - promoter analysis
tools:
  - "custom":
      description: "Custom R scripts"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: ""

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: TSV file containing ortholog groups
      pattern: "*.{tsv}"
  - gff3dir:
      type: directory
      description: Directory containing gff3 files
      pattern: "*/"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - fasta:
      type: file
      description: fasta file containing promoters
      pattern: "*.{fa}"
  - gff3:
    type: file
    description: gff3 file of promoters
    pattern: "*.{gff3}"

authors:
  - "@johannesnicolaus"
